name: Build Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install Additional Dependencies
        run: sudo apt-get install libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libxcb-res0-dev

      - name: Build Linux
        run: cd scripts && chmod +x ./build-all.sh && ./build-all.sh
